-- En pgAdmin 4, crea primero una base llamada SanitasFlow y conéctate a ella.
-- Después ejecuta este archivo en Query Tool.

CREATE TABLE IF NOT EXISTS "Pacientes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nombres" text NOT NULL,
    "ApellidoPaterno" text NOT NULL,
    "ApellidoMaterno" text NOT NULL,
    "Edad" integer NOT NULL,
    "Correo" varchar(320) NOT NULL UNIQUE,
    "PasswordHash" varchar(512) NOT NULL,
    "CreadoEnUtc" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "Medicos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nombre" text NOT NULL,
    "Especialidad" text NOT NULL,
    "Correo" text NOT NULL
);

CREATE TABLE IF NOT EXISTS "Especialidades" (
    "Id" varchar(450) PRIMARY KEY,
    "Nombre" text NOT NULL,
    "Descripcion" text NOT NULL
);

CREATE TABLE IF NOT EXISTS "Procedimientos" (
    "Id" varchar(450) PRIMARY KEY,
    "EspecialidadId" varchar(450) NOT NULL REFERENCES "Especialidades"("Id") ON DELETE RESTRICT,
    "Nombre" text NOT NULL,
    "Descripcion" text NOT NULL,
    "DuracionMin" integer NOT NULL,
    "Precio" numeric(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS "Citas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PacienteId" integer NOT NULL REFERENCES "Pacientes"("Id") ON DELETE CASCADE,
    "EspecialidadId" varchar(450) NOT NULL REFERENCES "Especialidades"("Id") ON DELETE RESTRICT,
    "ProcedimientoId" varchar(450) NOT NULL REFERENCES "Procedimientos"("Id") ON DELETE RESTRICT,
    "Fecha" date NOT NULL,
    "InicioMin" integer NOT NULL,
    "FinMin" integer NOT NULL,
    "Motivo" text NOT NULL,
    "Precio" numeric(10,2) NOT NULL,
    "Estado" varchar(32) NOT NULL,
    "CreadaEnUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "CK_Citas_Horario" CHECK ("FinMin" > "InicioMin")
);
CREATE INDEX IF NOT EXISTS "IX_Citas_EspecialidadId_Fecha" ON "Citas"("EspecialidadId", "Fecha");

CREATE TABLE IF NOT EXISTS "Pagos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CitaId" integer NOT NULL REFERENCES "Citas"("Id") ON DELETE CASCADE,
    "Monto" numeric(10,2) NOT NULL,
    "Metodo" text NOT NULL,
    "Estado" text NOT NULL,
    "ReferenciaExterna" text NOT NULL,
    "CreadoEnUtc" timestamp with time zone NOT NULL
);
